version: '3.8'
services:
  neoratel:
    image: node:18-alpine
    container_name: neoratel_dev
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "5173:5173"
      - "4004:4004"
    environment:
      - NODE_ENV=development
    command: sh -c "while true; do sleep 1000; done"
